const sampleListings = [
  {
    title: "Taj Lake Palace",
    description: "A luxurious heritage hotel floating on Lake Pichola.",
    image: {
      url: "https://th.bing.com/th/id/OIP.WkZ5pOkQs88FSE_BgnP3GwHaEw?rs=1&pid=ImgDetMain",
      filename: "taj-lake-palace",
    },
    price: 1000,
    location: "Udaipur, Rajasthan",
    country: "India",
    reviews: [],
    owner: "66295fe6fc13ae4792000001",
    geometry: {
      type: "Point",
      coordinates: [73.6856, 24.576],
    },
  },
  {
    title: "The Oberoi Amarvilas",
    description: "Lavish hotel with direct views of the Taj Mahal.",
    image: {
      url: "https://www.oberoihotels.com/-/media/oberoi-hotels/website-images/the-oberoi-amarvilas-agra/gallery/featured/amarvilas-gallery-featured-2-hotel-exterior-724x407.jpg",
      filename: "oberoi-amarvilas",
    },
    price: 520,
    location: "Agra, Uttar Pradesh",
    country: "India",
    reviews: [],
    owner: "66295fe6fc13ae4792000002",
    geometry: {
      type: "Point",
      coordinates: [78.0421, 27.1751],
    },
  },
  {
    title: "Backwater Haven Resort",
    description: "Serene resort by the Kerala backwaters.",
    image: {
      url: "https://1.bp.blogspot.com/-90hEnKC80UY/XpwxUdwfPFI/AAAAAAAAs-k/6tHQWq8SZyUgBBPttqyAotczuce8TAZ2gCLcBGAsYHQ/s1600/Kumakarom%2BLake%2BResort%2B14.JPG",
      filename: "backwater-haven",
    },
    price: 540,
    location: "Alleppey, Kerala",
    country: "India",
    reviews: [],
    owner: "66295fe6fc13ae4792000003",
    geometry: {
      type: "Point",
      coordinates: [76.3375, 9.4981],
    },
  },
  {
    title: "Royal Orchid Beach Resort",
    description: "Beachfront paradise in South Goa.",
    image: {
      url: "https://i.travelapi.com/lodging/2000000/1950000/1942700/1942691/be2a9d86_z.jpg",
      filename: "royal-orchid",
    },
    price: 870,
    location: "Goa",
    country: "India",
    reviews: [],
    owner: "66295fe6fc13ae4792000004",
    geometry: {
      type: "Point",
      coordinates: [73.7634, 15.2993],
    },
  },
  {
    title: "Himalayan Heights",
    description: "Escape into the mountains with breathtaking views.",
    image: {
      url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/633083152.jpg?k=6150363f9fb1363a56e41ef68520fb9d8501b298d663bd1102d2afd264e1b3ac&o=",
      filename: "himalayan-heights",
    },
    price: 720,
    location: "Manali, Himachal Pradesh",
    country: "India",
    reviews: [],
    owner: "66295fe6fc13ae4792000005",
    geometry: {
      type: "Point",
      coordinates: [77.1887, 32.2396],
    },
  },
  {
    title: "Urban Comfort Hotel",
    description: "Modern rooms with a rooftop bar in Tokyo.",
    image: {
      url: "https://www.myboutiquehotel.com/photos/4832/hotel-urban-madrid-142-1686231540-1110x700.jpg",
      filename: "urban-comfort",
    },
    price: 2150,
    location: "Shinjuku, Tokyo",
    country: "Japan",
    reviews: [],
    owner: "66295fe6fc13ae4792000006",
    geometry: {
      type: "Point",
      coordinates: [139.7034, 35.6938],
    },
  },
  {
    title: "Parisian Garden Inn",
    description: "Quaint hotel near the Eiffel Tower with garden café.",
    image: {
      url: "https://static.verychic.com/images/53146/en/desktop/17_10_2023_Hotel_Hilton_Garden_Inn_Paris_La_Villette_14.jpg",
      filename: "parisian-garden",
    },
    price: 2200,
    location: "Paris",
    country: "France",
    reviews: [],
    owner: "66295fe6fc13ae4792000007",
    geometry: {
      type: "Point",
      coordinates: [2.2945, 48.8584],
    },
  },
  {
    title: "Desert Pearl Camp",
    description: "Luxury tents in the heart of the Sahara.",
    image: {
      url: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/391365187.jpg?k=fcaf7feeb00208bd798bbb9d8c67a86fce2f55998a2dc8d74cd5e7b901c3ae48&o=&hp=1",
      filename: "desert-pearl",
    },
    price: 2110,
    location: "Merzouga",
    country: "Morocco",
    reviews: [],
    owner: "66295fe6fc13ae4792000008",
    geometry: {
      type: "Point",
      coordinates: [-3.9776, 31.1],
    },
  },
  {
    title: "Skyline Suites NYC",
    description: "Chic downtown stay with skyline views.",
    image: {
      url: "https://res.cloudinary.com/traveltripperweb/image/upload/c_limit,f_auto,h_2500,q_auto,w_2500/v1620070528/wu2posafmrsmlkgntli7.jpg",
      filename: "skyline-suites",
    },
    price: 2650,
    location: "New York City",
    country: "USA",
    reviews: [],
    owner: "66295fe6fc13ae4792000009",
    geometry: {
      type: "Point",
      coordinates: [-74.006, 40.7128],
    },
  },
  {
    title: "Coastal Charm B&B",
    description: "Beachfront bed and breakfast with local cuisine.",
    image: {
      url: "https://th.bing.com/th/id/OIP.GZxYo--3fJwze_THbCjlowHaE8?rs=1&pid=ImgDetMain",
      filename: "coastal-charm",
    },
    price: 1860,
    location: "Cape Town",
    country: "South Africa",
    reviews: [],
    owner: "66295fe6fc13ae4792000010",
    geometry: {
      type: "Point",
      coordinates: [18.4241, -33.9249],
    },
  },
  {
    title: "Icelandic Aurora Lodge",
    description: "Watch the northern lights from your private cabin.",
    image: {
      url: "https://media-cdn.tripadvisor.com/media/photo-s/0c/46/95/70/don-t-miss-this-hidden.jpg",
      filename: "aurora-lodge",
    },
    price: 2190,
    location: "Reykjavik",
    country: "Iceland",
    reviews: [],
    owner: "66295fe6fc13ae4792000011",
    geometry: {
      type: "Point",
      coordinates: [-21.8174, 64.1265],
    },
  },
  {
    title: "Balinese Bliss Villa",
    description: "Private villas with pools and rice field views.",
    image: {
      url: "https://unikbalivilla.com/wp-content/uploads/2023/07/unik-bali-villa-connectees-bliss345-for-rent-1.jpg",
      filename: "balinese-bliss",
    },
    price: 2100,
    location: "Ubud, Bali",
    country: "Indonesia",
    reviews: [],
    owner: "66295fe6fc13ae4792000012",
    geometry: {
      type: "Point",
      coordinates: [115.2625, -8.5069],
    },
  },
  {
    title: "Nordic Nest",
    description: "Sustainable hotel in the heart of Stockholm.",
    image: {
      url: "https://th.bing.com/th/id/R.31ec5b3ae0847efffd371baa1a9365e3?rik=UHObr0jI6KnZmQ&riu=http%3a%2f%2fjasdesignbuild.com%2fwp-content%2fuploads%2f2020%2f09%2fglopez1_1920.jpg&ehk=4kYHRHjR48cE42kihXA2AfqEseuerSa9sBzzsmrBPnA%3d&risl=&pid=ImgRaw&r=0",
      filename: "nordic-nest",
    },
    price: 2170,
    location: "Stockholm",
    country: "Sweden",
    reviews: [],
    owner: "66295fe6fc13ae4792000013",
    geometry: {
      type: "Point",
      coordinates: [18.0686, 59.3293],
    },
  },
  {
    title: "Amazon Rainforest Retreat",
    description: "Immersive jungle experience in eco-lodges.",
    image: {
      url: "https://th.bing.com/th/id/OIP.1TGhuVimLs49REn89tIfTQHaE8?rs=1&pid=ImgDetMain",
      filename: "amazon-retreat",
    },
    price: 1920,
    location: "Leticia",
    country: "Colombia",
    reviews: [],
    owner: "66295fe6fc13ae4792000014",
    geometry: {
      type: "Point",
      coordinates: [-69.9406, -4.2153],
    },
  },
  {
    title: "Vancouver Harbor Hotel",
    description: "Harbor-view rooms with modern Canadian charm.",
    image: {
      url: "https://th.bing.com/th/id/OIP.NANKmYKMRFoiB5oi4spKhAHaE8?rs=1&pid=ImgDetMain",
      filename: "vancouver-harbor",
    },
    price: 1200,
    location: "Vancouver",
    country: "Canada",
    reviews: [],
    owner: "66295fe6fc13ae4792000015",
    geometry: {
      type: "Point",
      coordinates: [-123.1216, 49.2827],
    },
  },
  {
    title: "Greek Isles Escape",
    description: "White-washed villas overlooking the Aegean Sea.",
    image: {
      url: "https://cdn.newsapi.com.au/image/v1/3e60246602ddc8ce4def1da1b30a1bfa",
      filename: "greek-isles",
    },
    price: 2240,
    location: "Santorini",
    country: "Greece",
    reviews: [],
    owner: "66295fe6fc13ae4792000016",
    geometry: {
      type: "Point",
      coordinates: [25.4615, 36.3932],
    },
  },
  {
    title: "Sydney Skyline Retreat",
    description: "Luxury hotel with harbor bridge views.",
    image: {
      url: "https://content.api.news/v3/images/bin/f88493cff9408ff4b916163d53a77c77",
      filename: "sydney-skyline",
    },
    price: 2230,
    location: "Sydney",
    country: "Australia",
    reviews: [],
    owner: "66295fe6fc13ae4792000017",
    geometry: {
      type: "Point",
      coordinates: [151.2093, -33.8688],
    },
  },
  {
    title: "Vienna Classical Hotel",
    description: "Baroque-style hotel in the city of music.",
    image: {
      url: "https://th.bing.com/th/id/OIP.2wttEjmD48Oj9oohnMFF6QHaEc?rs=1&pid=ImgDetMain",
      filename: "vienna-classical",
    },
    price: 2195,
    location: "Vienna",
    country: "Austria",
    reviews: [],
    owner: "66295fe6fc13ae4792000018",
    geometry: {
      type: "Point",
      coordinates: [16.3738, 48.2082],
    },
  },
  {
    title: "Dubai Desert Mirage",
    description: "Opulent oasis resort in the Arabian desert.",
    image: {
      url: "https://images.hellomagazine.com/horizon/original_aspect_ratio/a7e8fa67460c-ooroyalmirageexteriorsesplanadewideday0749master.jpg",
      filename: "dubai-mirage",
    },
    price: 3310,
    location: "Dubai",
    country: "UAE",
    reviews: [],
    owner: "66295fe6fc13ae4792000019",
    geometry: {
      type: "Point",
      coordinates: [55.2708, 25.2048],
    },
  },
  {
    title: "Florence Renaissance Hotel",
    description: "Stay in a 15th-century villa in Florence.",
    image: {
      url: "https://www.lartisien.com/blog/wp-content/uploads/2023/04/renaissance-suite_2-1024x796.jpeg",
      filename: "florence-hotel",
    },
    price: 2210,
    location: "Florence",
    country: "Italy",
    reviews: [],
    owner: "66295fe6fc13ae4792000020",
    geometry: {
      type: "Point",
      coordinates: [11.2558, 43.7696],
    },
  },
  {
    title: "Parisian Dream Hotel",
    description:
      "Charming hotel with Eiffel Tower views and Parisian elegance.",
    image: {
      url: "https://images.squarespace-cdn.com/content/v1/63a23d845d55cb35462bb987/1671577004255-0R1ALNYJGB75N29DKP98/image-asset.jpeg?format=1500w",
      filename: "paris-hotel",
    },
    price: 2220,
    location: "Paris",
    country: "France",
    reviews: [],
    owner: "66295fe6fc13ae4792000031",
    geometry: {
      type: "Point",
      coordinates: [2.3522, 48.8566],
    },
  },
  {
    title: "Tokyo Zen Inn",
    description: "Tranquil and modern hotel near Shibuya and Harajuku.",
    image: {
      url: "https://mustsharenews.com/wp-content/uploads/2019/03/hotel-zen-tokyo-cover.jpg",
      filename: "tokyo-zen",
    },
    price: 2180,
    location: "Tokyo",
    country: "Japan",
    reviews: [],
    owner: "66295fe6fc13ae4792000032",
    geometry: {
      type: "Point",
      coordinates: [139.6917, 35.6895],
    },
  },
  {
    title: "Santorini Cliffside Suites",
    description: "Luxury suites with white-washed domes and sunset sea views.",
    image: {
      url: "https://news.gtp.gr/wp-content/uploads/2016/09/Grand-Suite.jpeg",
      filename: "santorini-suites",
    },
    price: 2300,
    location: "Santorini",
    country: "Greece",
    reviews: [],
    owner: "66295fe6fc13ae4792000033",
    geometry: {
      type: "Point",
      coordinates: [25.4615, 36.3932],
    },
  },
  {
    title: "New York Central Stay",
    description:
      "Trendy hotel in Manhattan near Times Square and Central Park.",
    image: {
      url: "https://thafd.bing.com/th/id/OIP.N75wovHHAtV8KZ9WbDV_ZgAAAA?rs=1&pid=ImgDetMain",
      filename: "nyc-central",
    },
    price: 2250,
    location: "New York City",
    country: "USA",
    reviews: [],
    owner: "66295fe6fc13ae4792000034",
    geometry: {
      type: "Point",
      coordinates: [-73.9857, 40.758],
    },
  },
  {
    title: "Sydney Harbour Hotel",
    description: "Waterfront rooms with views of the Sydney Opera House.",
    image: {
      url: "https://www.ahstatic.com/photos/8779_roap2hv_00_p_2048x1536.jpg",
      filename: "sydney-harbour",
    },
    price: 3230,
    location: "Sydney",
    country: "Australia",
    reviews: [],
    owner: "66295fe6fc13ae4792000035",
    geometry: {
      type: "Point",
      coordinates: [151.2093, -33.8688],
    },
  },
  {
    title: "Dubai Marina Luxe",
    description: "High-rise hotel with rooftop pool and skyline views.",
    image: {
      url: "https://cdn.dubai-marina.com/media/internal_articles_image/1.1_Address_Dubai_Marina_Building_02pfEXL.jpg",
      filename: "dubai-marina",
    },
    price: 4280,
    location: "Dubai",
    country: "United Arab Emirates",
    reviews: [],
    owner: "66295fe6fc13ae4792000036",
    geometry: {
      type: "Point",
      coordinates: [55.2708, 25.2048],
    },
  },
  {
    title: "Rome Heritage Inn",
    description: "Boutique stay near the Colosseum with ancient charm.",
    image: {
      url: "https://images.luxuryescapes.com/q_auto:good,c_fill,g_auto,ar_16:9/dttead1163xhrk1dsmfe.jpeg",
      filename: "rome-heritage",
    },
    price: 2210,
    location: "Rome",
    country: "Italy",
    reviews: [],
    owner: "66295fe6fc13ae4792000037",
    geometry: {
      type: "Point",
      coordinates: [12.4964, 41.9028],
    },
  },
  {
    title: "Bangkok Sky Hotel",
    description: "Urban hotel with rooftop views and authentic Thai cuisine.",
    image: {
      url: "https://baiyokesky.baiyokehotel.com/images/new_gallery/gallery-33.jpg",
      filename: "bangkok-sky",
    },
    price: 2140,
    location: "Bangkok",
    country: "Thailand",
    reviews: [],
    owner: "66295fe6fc13ae4792000038",
    geometry: {
      type: "Point",
      coordinates: [100.5018, 13.7563],
    },
  },
  {
    title: "London Garden Suites",
    description: "Peaceful garden hotel minutes from Buckingham Palace.",
    image: {
      url: "https://thafd.bing.com/th/id/OIP.SCMX6C9qoG31HZD3xxiKKQHaEo?rs=1&pid=ImgDetMain",
      filename: "london-garden",
    },
    price: 2240,
    location: "London",
    country: "United Kingdom",
    reviews: [],
    owner: "66295fe6fc13ae4792000039",
    geometry: {
      type: "Point",
      coordinates: [-0.1276, 51.5074],
    },
  },
  {
    title: "Cape Town Bayview Lodge",
    description: "Modern beach lodge with views of Table Mountain.",
    image: {
      url: "https://th.bing.com/th/id/R.fa03837b4fcefa45b632e9a2be2ca67d?rik=jUBPWNYF7tuniw&riu=http%3a%2f%2froomsforafrica.com%2fnew-gallery%2fbayviewguesthouse_1_18-x_large.jpg&ehk=EGnA8TufM9x%2foO0GNgDB1c7D7NqoAPPRXystCH0%2bjmw%3d&risl=&pid=ImgRaw&r=0",
      filename: "cape-town-bayview",
    },
    price: 1190,
    location: "Cape Town",
    country: "South Africa",
    reviews: [],
    owner: "66295fe6fc13ae4792000040",
    geometry: {
      type: "Point",
      coordinates: [18.4241, -33.9249],
    },
  },
];

module.exports = { data: sampleListings };
